### ISSUE TITLE
image file-integrity-operator-index has no latest tag

### ISSUE THREAD

**Issue by jandradap** [openshift/file-integrity-operator#121]
The catalog-source points to the [latest tag](https://github.com/openshift/file-integrity-operator/blob/master/deploy/olm-catalog/catalog-source.yaml):

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: file-integrity-operator
  namespace: openshift-marketplace
spec:
  displayName: File Integrity Operator
  publisher: github.com/openshift/file-integrity-operator
  sourceType: grpc
  image: quay.io/file-integrity-operator/file-integrity-operator-index:latest
```

In the registry there is no such tag, if I edit the catalog pointing to tag 0.1.6 it works correctly.

https://quay.io/repository/file-integrity-operator/file-integrity-operator-index?tab=tags
