### ISSUE TITLE
[ocp4.8] FIO Servicemonitor not accessible by openshift-user-workload-monitoring prometheus instance

### ISSUE THREAD

**Issue by felixkrohn** [openshift/file-integrity-operator#194]
file-integrity-operator.v0.1.18 running on OCP 4.8.5 with default config for openshift-user-workload-monitoring.
In the logs of _prometheus-operator_ in the _openshift-user-workload-monitoring_ namespace I can see logs like this:

> level=warn ts=2021-08-23T21:16:00.305307242Z caller=operator.go:1703 component=prometheusoperator msg="skipping servicemonitor" error="it accesses file system via bearer token file which Prometheus specification prohibits" servicemonitor=openshift-file-integrity/metrics namespace=openshift-user-workload-monitoring prometheus=user-workload

Are there already plans to change this default behaviour, or to make it configurable?

**Comment by felixkrohn** [comment]
ok, probably my own fault, I noticed that in the last version the namespace is labeled to use cluster-monitoring instead of user-workload-monitoring:
https://github.com/openshift/file-integrity-operator/commit/f7a84024bcad5f904cba744c268785fa55f8e073#diff-bf3069216d02240489226628f6447441b91fed3efcd6a635316100adc204dcebR4-R5
I?ll try adding that.

**Comment by JAORMX** [comment]
@felixkrohn let us know if that fixed it for you

**Comment by felixkrohn** [comment]
more or less... I discovered that there was a seemingly bogus rolebinding created in the openshift-file-integrity namespace:
```
[...]
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: file-integrity-operator.v0.1.18-prometheus-k8s-6bd9f78c69
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-file-integrity             <====
```
after adding a set of role/-bindings with the correct nymespace, I now get the metrics.
According to ownerRefs the "broken" rb was created by
```
    kind: ClusterServiceVersion
    name: file-integrity-operator.v0.1.18
```
not sure if that's worth a separate issue though?
