### ISSUE TITLE
Operator does not expose a native way to modify nodeSelector

### ISSUE THREAD

**Issue by toredash** [openshift/file-integrity-operator#206]
Request that the operator gets support to modify the [nodeSelector on installation](https://github.com/openshift/file-integrity-operator/blob/d78a332c4a6ce3b8528a3e0745a8eaa1b0dbd2cd/deploy/operator.yaml#L55)

Currently this is hard-coded to run on node-role master. The Deployment can be altered, but as patch operations does not have a way to delete a field, its hard to automate the installation process.

If this can be linked to a customer in Red Hat to add prioritization to it, let me know

**Comment by toredash** [comment]
In this env our scheduler.config is set to disallow pod placement on masters, and use the worker label as the defaultNodeSelector.

Example:
```
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  defaultNodeSelector: node-role.kubernetes.io/worker=
  masterScheduable: false
````

As the value is hard-coded in the operator, I'm not able to identify a way around this other than to modify the Deployment after the operator is installed.

The reason this env does not allow placement on master nodes, is that the master nodes are defined as node that should only run the critical components in the infrastructure. infra-nodes are used in this env as well to host ingress and other functions on the infra nodes.
