### ISSUE TITLE
Set resource limits for containers

### ISSUE THREAD

**Issue by bigg01** [openshift/file-integrity-operator#68]
As a Platform Engineer I need to control usage of CPU Memory per Container. 
Please add ressource limits:

```
resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 200Mi
            cpu: 400m
```

The Aide PODS were running for a day and used 1.6 Gb of memory for no reason.

cheers
