### ISSUE TITLE
Duplicate CRDs

### ISSUE THREAD

**Issue by pichuang** [openshift/file-integrity-operator#73]
In v0.1.3, the CRDs are [duplicate][1]

```yaml
  customresourcedefinitions:
    owned:
    - description: FileIntegrity is the Schema for the fileintegrities API
      kind: FileIntegrity
      name: fileintegrities.fileintegrity.openshift.io
      version: v1alpha1
    - description: FileIntegrity is the Schema for the fileintegrities API
      kind: FileIntegrity
      name: fileintegrities.fileintegrity.openshift.io
      version: v1alpha1
    - description: FileIntegrityNodeStatus defines the status of a specific node
      kind: FileIntegrityNodeStatus
      name: fileintegritynodestatuses.fileintegrity.openshift.io
      version: v1alpha1
    - description: FileIntegrityNodeStatus defines the status of a specific node
      kind: FileIntegrityNodeStatus
      name: fileintegritynodestatuses.fileintegrity.openshift.io
      version: v1alpha1
```

It also have the same issue in [v0.1.2][2]

[1]: https://github.com/openshift/file-integrity-operator/blob/master/deploy/olm-catalog/file-integrity-operator/0.1.3/file-integrity-operator.v0.1.3.clusterserviceversion.yaml#L34-L49
[2]: https://github.com/openshift/file-integrity-operator/blob/master/deploy/olm-catalog/file-integrity-operator/0.1.2/file-integrity-operator.v0.1.2.clusterserviceversion.yaml#L34-L49
